# ================================================================
# Bayesian UQ for Porous Media — build system
#
# Targets
#   make all        (default) generate figures then compile PDF
#   make figures    generate Python figures only
#   make pdf        compile LaTeX (requires figures to exist)
#   make clean      remove LaTeX auxiliary files
#   make veryclean  also remove generated figures and PDF
# ================================================================

PYTHON   := python3
LATEX    := pdflatex -interaction=nonstopmode -halt-on-error

MAIN := report

# ── figure stamp files (generated by the Python scripts) ───────
UQ_STAMP   := figures/.stamp
CONJ_STAMP := conjugate_priors/figures/.stamp

# ── Python source dependencies ──────────────────────────────────
UQ_SRC   := demo_uq.py \
             uq_porous_media/distributions.py \
             uq_porous_media/gaussian_field.py \
             uq_porous_media/darcy_1d.py \
             uq_porous_media/inference.py \
             uq_porous_media/mcmc.py

CONJ_SRC := conjugate_priors/demo_conjugate.py \
            conjugate_priors/conjugate_pairs.py

# ================================================================
.PHONY: all figures pdf clean veryclean

all: pdf

# ── PDF: two pdflatex passes to resolve cross-refs and TOC ─────
pdf: $(MAIN).pdf

$(MAIN).pdf: $(MAIN).tex $(UQ_STAMP) $(CONJ_STAMP)
	$(LATEX) $(MAIN).tex
	$(LATEX) $(MAIN).tex

# ── Figure generation ───────────────────────────────────────────
figures: $(UQ_STAMP) $(CONJ_STAMP)

$(UQ_STAMP): $(UQ_SRC)
	mkdir -p figures
	$(PYTHON) demo_uq.py
	@touch $@

$(CONJ_STAMP): $(CONJ_SRC)
	$(PYTHON) conjugate_priors/demo_conjugate.py
	@touch $@

# ── Housekeeping ────────────────────────────────────────────────
clean:
	rm -f $(MAIN).aux $(MAIN).log $(MAIN).out $(MAIN).toc

veryclean: clean
	rm -f $(MAIN).pdf
	rm -rf figures conjugate_priors/figures
